<!DOCTYPE html>
<html lang="en" dir="ltr"><head>
  
                           
     


<meta charset="UTF-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
<meta name="generator" content="Hugo 0.96.0" />
<title>9. Correspondence Analysis (CA) | BCB R Stats Pages</title>


<meta property="twitter:site" content="@ajsmit">
<meta property="twitter:creator" content="@ajsmit">







  
    
  
<meta name="description" content="What you need to know upfront.">


<meta property="og:site_name" content="BCB R Stats Pages">
<meta property="og:title" content="9. Correspondence Analysis (CA) | BCB R Stats Pages">
<meta property="og:description" content="What you need to know upfront." />
<meta property="og:type" content="page" />
<meta property="og:url" content="/collection/quantecol/chapters/09-ca/" />
<meta property="og:locale" content="en">




    
        <meta property="og:image" content="/img/papillons.jpg" >
        <meta property="twitter:card" content="summary_large_image">
        <meta name="twitter:image" content="/img/papillons.jpg" >
    
  <meta itemprop="name" content="9. Correspondence Analysis (CA)">
<meta itemprop="description" content="CA is an eigenvalue method that can be applied to calculate the degree of ‘correspondence’ between the rows and columns of a presence-absence or abundance species table. We say that CA maximises the correspondence between species scores and sample scores, whereas a PCA maximises the variance explained. The technique is best applied to a species dataset where the species (in the columns) show unimodal distributions across sites (down the rows)."><meta itemprop="datePublished" content="2021-01-01T00:00:00+00:00" />
<meta itemprop="dateModified" content="2021-01-01T00:00:00+00:00" />
<meta itemprop="wordCount" content="2629">
<meta itemprop="keywords" content="" />
  
  
  <!--[if IE]><script src="//html5shiv.googlecode.com/svn/trunk/html5.js"></script><![endif]-->
  <link rel="shortcut icon" href="/img/favicon.ico" type="image/x-icon">
  <link rel="icon" href="/img/favicon.ico" type="image/x-icon">
  
  
  <link rel="stylesheet" href="/style.main.min.13dd27d3efb7ed4ad82be3040182ddbf5ab9d3b4d6d01f0ba3930845932fce66.css" integrity="sha256-E90n0&#43;&#43;37UrYK&#43;MEAYLdv1q507TW0B8Lo5MIRZMvzmY=" media="screen">
  
  
  <script src="/panelset.min.8f4cba0107356728f266d94a12a4d18ef504eda8a9a284cda73675bae7884a68.js" type="text/javascript"></script>
  
  
  <script src="/main.min.318ee9c0652bba0149e7503c97e37e638937f3a9cad9233e6d0ba00bf7a46a5e.js" type="text/javascript"></script>
</head>
<body>
      <div class="grid-container single-series">
<header class="site-header pt4 pb2 mb4 bb b--transparent ph5 headroom z-max" role="banner">
  <nav class="site-nav db dt-l w-100" role="navigation">
    <a class="site-brand db dtc-l v-mid link no-underline w-100 w-33-l tc tl-l" href="/" title="Home">
      <img src="/img/xaringan-outline.png" class="dib db-l h2 w-auto" alt="BCB R Stats Pages">
    </a>
    <div class="site-links db dtc-l v-mid w-100 w-47-l tc tr-l mt3 mt0-l ttu tracked">
      
        
        
        
      <a class="link f6 f5-l dib pv1 ph2 " href="/about/" title="About AJ Smit">About</a>
      
        
        
        
      <a class="link f6 f5-l dib pv1 ph2 " href="/workshops/" title="BCB Hons">BCB Hons</a>
      
        
        
        
      <a class="link f6 f5-l dib pv1 ph2 " href="/project/" title="Project Portfolio">Projects</a>
      
        
        
        
      <a class="link f6 f5-l dib pv1 ph2 active" href="/collection/" title="R Courses">R Courses</a>
      
      
    </div>
  </nav>
</header>


<main class="page-main ph4 pt4" role="main">
  <section class="page-content mw7 center">
    <article class="post-content pa0 pr3-l">
      <header class="post-header">
        <h4 class="breadcrumb pb5">

  
    
      
  
    
      
  
    
      
  

    
    
      <a href="/collection/">B.Sc. (Hons.) R modules</a>
    
  

    
    
      <a href="/collection/quantecol/">BCB743</a>
    
  

    
    
      9. Correspondence Analysis (CA)
    
  

</h4>




        
        <h1 class="f1 lh-solid measure-narrow mb3 fw4">9. Correspondence Analysis (CA)</h1>
        
        <p class="f6 measure lh-copy mv1"></p>
        <p class="f7 db mv0 ttu">January 1, 2021</p>
        
        
      
        
      </header>
      <section class="post-body pt5 pb4">
        


<!--- # Topic 9: Correspondence Analysis (CA) --->
<p>CA is an eigenvalue method that can be applied to calculate the degree of ‘correspondence’ between the rows and columns of a presence-absence or abundance species table. We say that CA maximises the correspondence between species scores and sample scores, whereas a PCA maximises the variance explained. The technique is best applied to a species dataset where the species (in the columns) show unimodal distributions across sites (down the rows). CA represents the distances among sites and among species by the <span class="math inline">\(\chi^{2}\)</span> distance metric (rather than Euclidian distances in PCA), which does not suffer from the <a href="https://www.davidzeleny.net/anadat-r/doku.php/en:similarity#:~:text=Chi%2Dsquare%20distances.-,Double%2Dzero%20problem,which%20similarity%2Fdistance%20is%20calculated.&amp;text=The%20fact%20that%20the%20mesic,or%20difference%20between%20both%20samples.">double-zero problem</a>. Some ecologists argue that CA might be too much influenced by rare species. In ordination diagrams, species and sites are also represented by points as per usual convention. The relative positions of these points (species vs sites, species vs. other species, or sites vs. other sites) indicate how strongly they ‘correspond’ to one another.</p>
<p>CA therefore finds the ordination space that answers questions such as, “Which sites do my species prefer?” or “Which sites to my species correspond to?” (from <a href="https://sites.google.com/site/mb3gustame/indirect-gradient-analysis/ca">GUSTA ME</a>). Also see David Zelený’s <a href="https://www.davidzeleny.net/anadat-r/doku.php/en:ca_dca">Analysis of community ecology data in R</a>.</p>
<div id="set-up-the-analysis-environment" class="section level2">
<h2>Set-up the analysis environment</h2>
<pre class="r"><code>library(tidyverse)
library(vegan)</code></pre>
</div>
<div id="the-doubs-river-data" class="section level2">
<h2>The Doubs River data</h2>
<p>This time we work with the species data:</p>
<pre class="r"><code>spe &lt;- read.csv(&quot;/Users/ajsmit/Dropbox/R/workshops/Quantitative_Ecology/Num_Ecol_R_book_ed1/DoubsSpe.csv&quot;)
spe &lt;- dplyr::select(spe, -1)
head(spe, 8)</code></pre>
<pre><code>##   Cogo Satr Phph Babl Thth Teso Chna Pato Lele Sqce Baba Albi Gogo Eslu Pefl
## 1    0    3    0    0    0    0    0    0    0    0    0    0    0    0    0
## 2    0    5    4    3    0    0    0    0    0    0    0    0    0    0    0
## 3    0    5    5    5    0    0    0    0    0    0    0    0    0    1    0
## 4    0    4    5    5    0    0    0    0    0    1    0    0    1    2    2
## 5    0    2    3    2    0    0    0    0    5    2    0    0    2    4    4
## 6    0    3    4    5    0    0    0    0    1    2    0    0    1    1    1
## 7    0    5    4    5    0    0    0    0    1    1    0    0    0    0    0
## 8    0    0    0    0    0    0    0    0    0    0    0    0    0    0    0
##   Rham Legi Scer Cyca Titi Abbr Icme Gyce Ruru Blbj Alal Anan
## 1    0    0    0    0    0    0    0    0    0    0    0    0
## 2    0    0    0    0    0    0    0    0    0    0    0    0
## 3    0    0    0    0    0    0    0    0    0    0    0    0
## 4    0    0    0    0    1    0    0    0    0    0    0    0
## 5    0    0    2    0    3    0    0    0    5    0    0    0
## 6    0    0    0    0    2    0    0    0    1    0    0    0
## 7    0    0    0    0    0    0    0    0    0    0    0    0
## 8    0    0    0    0    0    0    0    0    0    0    0    0</code></pre>
</div>
<div id="do-the-ca" class="section level2">
<h2>Do the CA</h2>
<p>The <strong>vegan</strong> function <code>cca()</code> can be used for CA and Constrained Correspondence Analysis (CCA). When we do not specify constraints, as we do here, we will do a simple CA:</p>
<pre class="r"><code>spe_ca &lt;- cca(spe)</code></pre>
<pre><code>## Error in cca.default(spe): all row sums must be &gt;0 in the community data matrix</code></pre>
<p>Okay, so there’s a problem. The error message says that at least one of the rows sums to 0. Which one?</p>
<pre class="r"><code>apply(spe, 1, sum)</code></pre>
<pre><code>##  [1]  3 12 16 21 34 21 16  0 14 14 11 18 19 28 33 40 44 42 46 56 62 72  4 15 11
## [26] 43 63 70 87 89</code></pre>
<p>We see that the offending row is row 8, so we can omit it. This function will omit any row that sums to zero (or less):</p>
<pre class="r"><code>spe &lt;- spe[rowSums(spe) &gt; 0, ]
head(spe, 8)</code></pre>
<pre><code>##   Cogo Satr Phph Babl Thth Teso Chna Pato Lele Sqce Baba Albi Gogo Eslu Pefl
## 1    0    3    0    0    0    0    0    0    0    0    0    0    0    0    0
## 2    0    5    4    3    0    0    0    0    0    0    0    0    0    0    0
## 3    0    5    5    5    0    0    0    0    0    0    0    0    0    1    0
## 4    0    4    5    5    0    0    0    0    0    1    0    0    1    2    2
## 5    0    2    3    2    0    0    0    0    5    2    0    0    2    4    4
## 6    0    3    4    5    0    0    0    0    1    2    0    0    1    1    1
## 7    0    5    4    5    0    0    0    0    1    1    0    0    0    0    0
## 9    0    0    1    3    0    0    0    0    0    5    0    0    0    0    0
##   Rham Legi Scer Cyca Titi Abbr Icme Gyce Ruru Blbj Alal Anan
## 1    0    0    0    0    0    0    0    0    0    0    0    0
## 2    0    0    0    0    0    0    0    0    0    0    0    0
## 3    0    0    0    0    0    0    0    0    0    0    0    0
## 4    0    0    0    0    1    0    0    0    0    0    0    0
## 5    0    0    2    0    3    0    0    0    5    0    0    0
## 6    0    0    0    0    2    0    0    0    1    0    0    0
## 7    0    0    0    0    0    0    0    0    0    0    0    0
## 9    0    0    0    0    1    0    0    0    4    0    0    0</code></pre>
<p>Now we are ready for the CA:</p>
<pre class="r"><code>spe_ca &lt;- cca(spe)
spe_ca</code></pre>
<pre><code>## Call: cca(X = spe)
## 
##               Inertia Rank
## Total           1.167     
## Unconstrained   1.167   26
## Inertia is scaled Chi-square 
## 
## Eigenvalues for unconstrained axes:
##    CA1    CA2    CA3    CA4    CA5    CA6    CA7    CA8 
## 0.6010 0.1444 0.1073 0.0834 0.0516 0.0418 0.0339 0.0288 
## (Showing 8 of 26 unconstrained eigenvalues)</code></pre>
<p>The more verbose <code>summary()</code> output:</p>
<pre class="r"><code>summary(spe_ca)</code></pre>
<pre><code>## 
## Call:
## cca(X = spe) 
## 
## Partitioning of scaled Chi-square:
##               Inertia Proportion
## Total           1.167          1
## Unconstrained   1.167          1
## 
## Eigenvalues, and their contribution to the scaled Chi-square 
## 
## Importance of components:
##                         CA1    CA2     CA3     CA4     CA5     CA6     CA7
## Eigenvalue            0.601 0.1444 0.10729 0.08337 0.05158 0.04185 0.03389
## Proportion Explained  0.515 0.1237 0.09195 0.07145 0.04420 0.03586 0.02904
## Cumulative Proportion 0.515 0.6387 0.73069 0.80214 0.84634 0.88220 0.91124
##                           CA8     CA9     CA10     CA11     CA12     CA13
## Eigenvalue            0.02883 0.01684 0.010826 0.010142 0.007886 0.006123
## Proportion Explained  0.02470 0.01443 0.009278 0.008691 0.006758 0.005247
## Cumulative Proportion 0.93594 0.95038 0.959655 0.968346 0.975104 0.980351
##                           CA14     CA15     CA16     CA17     CA18     CA19
## Eigenvalue            0.004867 0.004606 0.003844 0.003067 0.001823 0.001642
## Proportion Explained  0.004171 0.003948 0.003294 0.002629 0.001562 0.001407
## Cumulative Proportion 0.984522 0.988470 0.991764 0.994393 0.995955 0.997362
##                           CA20      CA21      CA22      CA23      CA24
## Eigenvalue            0.001295 0.0008775 0.0004217 0.0002149 0.0001528
## Proportion Explained  0.001110 0.0007520 0.0003614 0.0001841 0.0001309
## Cumulative Proportion 0.998472 0.9992238 0.9995852 0.9997693 0.9999002
##                            CA25      CA26
## Eigenvalue            8.949e-05 2.695e-05
## Proportion Explained  7.669e-05 2.310e-05
## Cumulative Proportion 1.000e+00 1.000e+00
## 
## Scaling 2 for species and site scores
## * Species are scaled proportional to eigenvalues
## * Sites are unscaled: weighted dispersion equal on all dimensions
## 
## 
## Species scores
## 
##           CA1       CA2      CA3       CA4       CA5       CA6
## Cogo  1.50075 -1.410293  0.26049 -0.307203  0.271777 -0.003465
## Satr  1.66167  0.444129  0.57571  0.166073 -0.261870 -0.326590
## Phph  1.28545  0.285328 -0.04768  0.018126  0.043847  0.200732
## Babl  0.98662  0.360900 -0.35265 -0.009021 -0.012231  0.253429
## Thth  1.55554 -1.389752  0.80505 -0.468471  0.471301  0.225409
## Teso  0.99709 -1.479902 -0.48035  0.079397 -0.105715 -0.332445
## Chna -0.54916 -0.051534  0.01123 -0.096004 -0.382763  0.134807
## Pato -0.18478 -0.437710 -0.57438  0.424267 -0.587150  0.091866
## Lele  0.01337 -0.095342 -0.57672  0.212017  0.126668 -0.389103
## Sqce  0.01078  0.140577 -0.34811 -0.538268  0.185286  0.167087
## Baba -0.33363 -0.300682 -0.04929  0.170961 -0.157203  0.103068
## Albi -0.38357 -0.255310 -0.20136  0.374057 -0.385866  0.239001
## Gogo -0.32152 -0.034382 -0.07423 -0.031236  0.014417 -0.156351
## Eslu -0.26165  0.187282  0.00617  0.183771  0.295142 -0.262808
## Pefl -0.28913  0.121044 -0.18919  0.367615  0.218087 -0.163675
## Rham -0.60298 -0.057369  0.20341  0.214299 -0.050977  0.211926
## Legi -0.58669 -0.082467  0.21198  0.050175 -0.120456  0.108724
## Scer -0.61815  0.124733  0.13339  0.147190  0.317736 -0.340380
## Cyca -0.57951 -0.110732  0.20173  0.308547  0.006854  0.153224
## Titi -0.37880  0.138023 -0.07825  0.095793  0.256285 -0.029245
## Abbr -0.70235  0.011155  0.40242  0.211582  0.138186  0.132297
## Icme -0.73238 -0.009098  0.55678  0.321852  0.281812  0.172271
## Gyce -0.69300  0.038971  0.37688 -0.183965 -0.051945 -0.011126
## Ruru -0.44181  0.176915 -0.23691 -0.345104  0.129676 -0.043802
## Blbj -0.70928  0.032317  0.40924  0.030224  0.049050  0.114560
## Alal -0.63114  0.053594  0.15204 -0.661381 -0.414796 -0.206611
## Anan -0.63578 -0.041894  0.30093  0.224044  0.030444  0.203160
## 
## 
## Site scores (weighted averages of species scores)
## 
##         CA1       CA2        CA3      CA4      CA5      CA6
## 1   2.76488  3.076306  5.3657489  1.99192 -5.07714 -7.80447
## 2   2.27540  2.565531  1.2659130  0.87538 -1.89139 -0.13887
## 3   2.01823  2.441224  0.5144079  0.79436 -1.03741  0.56015
## 4   1.28485  1.935664 -0.2509482  0.76470  0.54752  0.10579
## 5   0.08875  1.015182 -1.4555434  0.47672  2.69249 -2.92498
## 6   1.03188  1.712163 -0.9544059  0.01584  0.91932  0.39856
## 7   1.91427  2.256208 -0.0001407  0.39844 -1.07017  0.32127
## 9   0.25591  1.443008 -2.5777721 -3.41400  2.36613  2.71741
## 10  1.24517  1.526391 -1.9635663 -0.41230  0.69647  1.51859
## 11  2.14501  0.110278  1.6108693 -0.82023  0.53918  1.01153
## 12  2.17418 -0.251649  1.5845397 -0.81483  0.52623  1.05501
## 13  2.30944 -2.034439  1.9181448 -0.60481  0.64435 -0.14844
## 14  1.87141 -2.262503  1.1066796 -0.80840  1.09542  0.11038
## 15  1.34659 -1.805967 -0.6441505 -0.52803  0.76871 -0.67165
## 16  0.70214 -1.501167 -1.9735888  0.98502 -0.93585 -1.27168
## 17  0.28775 -0.836803 -1.2259108  0.73302 -1.57036  0.57315
## 18  0.05299 -0.647950 -0.9234228  0.35770 -0.95401  0.77738
## 19 -0.20584 -0.007252 -1.0154343  0.07041 -1.03450  0.51442
## 20 -0.57879  0.042849 -0.3660551 -0.15019 -0.61357  0.10115
## 21 -0.67320  0.038875  0.1194956  0.17256 -0.14686 -0.12018
## 22 -0.71933  0.014694  0.2204186  0.13598  0.09459 -0.02068
## 23 -0.70438  0.735398 -0.6546250 -6.61523 -2.49441 -1.73215
## 24 -0.83976  0.390120  0.5605295 -4.38864 -2.56916 -0.96702
## 25 -0.68476  0.418842 -0.2860819 -2.80336 -0.37540 -3.93791
## 26 -0.75808  0.210204  0.5894091 -0.70004 -0.01880 -0.10779
## 27 -0.75046  0.100869  0.5531191 -0.12946  0.29164  0.11280
## 28 -0.77878  0.088976  0.7379012  0.05204  0.40940  0.43236
## 29 -0.60815 -0.203235  0.5522726  0.43621  0.15010  0.25618
## 30 -0.80860 -0.019592  0.6686542  0.88136  0.52744  0.16456</code></pre>
<p>The output looks similar to that of a PCA. The important things to note are the <strong>inertia</strong> (unconstrained and total inertia are the same), the <strong>Eigenvalues for the unconstrained axes</strong>, the <strong>Species scores,</strong> and the <strong>Site scores</strong>. Their interpretation is the same as before, but we can reiterate. Let us calculate the total inertia:</p>
<pre class="r"><code>round(sum(spe_ca$CA$eig), 5)</code></pre>
<pre><code>## [1] 1.16691</code></pre>
<p>The inertia for the first axis (CA1) is:</p>
<pre class="r"><code>round(spe_ca$CA$eig[1], 5)</code></pre>
<pre><code>##     CA1 
## 0.60099</code></pre>
<p>The inertia of CA1 <em>and</em> CA2 is:</p>
<pre class="r"><code>round(sum(spe_ca$CA$eig[1:2]), 5)</code></pre>
<pre><code>## [1] 0.74536</code></pre>
<p>The fraction of the variance explained by CA1 and CA2 is:</p>
<pre class="r"><code>round(sum(spe_ca$CA$eig[1:2]) / sum(spe_ca$CA$eig) * 100, 2) # result in %</code></pre>
<pre><code>## [1] 63.87</code></pre>
<p>Above, the value is the same one as in <strong>Cumulative Proportion</strong> in the <code>summary(spe_ca)</code> output under the CA2 column.</p>
<p>Species scores are <em>actual</em> species scores as they now relate to species data. The most positive and most negative eigenvectors (or loadings) indicate those species that dominate in their influence along particular CA axes. For example, CA1 will be most heavily loaded by the species Cogo and Satr (eigenvectors of 1.50075 and 1.66167, respectively). If there is an environmental gradient, it will be these species that will be most affected. At the very least, we can say that the contributions of these species are having an overriding influence on the community differences seen between sites.</p>
<p>Site scores are also as seen earlier in PCA. The highest positive or negative loadings indicate sites that are dispersed far apart on the biplot (in ordination space). They will have large differences in fish community composition.</p>
<p>Please see <em>Numerical Ecology in R</em> (pp. 133 to 140). There you will find explanations for how to interpret the ordinations and the ordination diagrams shown below.</p>
</div>
<div id="ordination-diagrams" class="section level2">
<h2>Ordination diagrams</h2>
<p>The biplots for the above ordination are given here:</p>
<pre class="r"><code>plot(spe_ca, scaling = 1, main = &quot;CA fish abundances - biplot scaling 1&quot;)</code></pre>
<p><img src="/collection/quantecol/chapters/09-CA_files/figure-html/unnamed-chunk-12-1.png" width="672" /></p>
<pre class="r"><code>plot(spe_ca, scaling = 2, main = &quot;CA fish abundances - biplot scaling 2&quot;)</code></pre>
<p><img src="/collection/quantecol/chapters/09-CA_files/figure-html/unnamed-chunk-12-2.png" width="672" /></p>
<p><strong>Scaling 1:</strong> This scaling <em>emphasises relationships between rows</em> accurately in low-dimensional ordination space. Distances among objects (samples or sites) in the biplot are approximations of their <span class="math inline">\(\chi^{2}\)</span> distances in multidimensional space. Objects found near a point representing a species are likely to contain a high contribution of that species.</p>
<p><strong>Scaling 2:</strong> This scaling <em>emphasises relationships between columns</em> accurately in low-dimensional ordination space. Distances among objects (samples or sites) in the biplot are not approximations of their <span class="math inline">\(\chi^{2}\)</span> distances in multidimensional space, but the distances among species are. Species positioned close to the point representing an object (a sample or site) are more likely to be found in that object or to have higher frequency there.</p>
<p>Below are biplots with site and species scores for four selected species. The plots are augmented with response surfaces made with penalised splines for each species showing i) where it are most abundant and ii) the direction of the response (here non-linear). On the last panel (bottom right) I also project vectors for the environmental drivers and mark the ones with the greatest influence in red. Lastly, the point size scales with species scores:</p>
<pre class="r"><code>require(&#39;viridis&#39;)</code></pre>
<pre><code>## Loading required package: viridis</code></pre>
<pre><code>## Loading required package: viridisLite</code></pre>
<pre class="r"><code>palette(viridis(8))
par(mar = c(4, 4, 0.9, 0.5) + .1, mfrow = c(2, 2))
with(spe, tmp &lt;- ordisurf(spe_ca ~ Satr, bubble = 3,
                          family = quasipoisson, knots = 2, col = 6,
                          display = &quot;sites&quot;, main = &quot;Satr&quot;))
abline(h = 0, v = 0, lty = 3)
with(spe, tmp &lt;- ordisurf(spe_ca ~ Scer, bubble = 3,
                          family = quasipoisson, knots = 2, col = 6,
                          display = &quot;sites&quot;, main = &quot;Scer&quot;))
abline(h = 0, v = 0, lty = 3)
with(spe, tmp &lt;- ordisurf(spe_ca ~ Teso, bubble = 3,
                          family = quasipoisson, knots = 2, col = 6,
                          display = &quot;sites&quot;, main = &quot;Teso&quot;))
abline(h = 0, v = 0, lty = 3)
with(spe, tmp &lt;- ordisurf(spe_ca ~ Cogo, bubble = 3,
                          family = quasipoisson, knots = 2, col = 6,
                          display = &quot;sites&quot;, main = &quot;Cogo&quot;))
abline(h = 0, v = 0, lty = 3)

# a posteriori projection of environmental variables in a CA
env &lt;- read.csv(&quot;/Users/ajsmit/Dropbox/R/workshops/Quantitative_Ecology/Num_Ecol_R_book_ed1/DoubsEnv.csv&quot;)
env &lt;- dplyr::select(env, -1)

# we removed the 8th row in spe, so do it here too
env &lt;- dplyr::slice(env, -8)

# the last plot produced (CA scaling 2) must be active
# scaling 2 is default
(spe_ca_env &lt;- envfit(spe_ca, env, scaling = 2))</code></pre>
<pre><code>## 
## ***VECTORS
## 
##          CA1      CA2     r2 Pr(&gt;r)    
## dfs -0.94799 -0.31830 0.6892  0.001 ***
## alt  0.81159  0.58423 0.8078  0.001 ***
## slo  0.73753  0.67531 0.2976  0.001 ***
## flo -0.92837 -0.37166 0.4440  0.001 ***
## pH   0.50723 -0.86181 0.0908  0.215    
## har -0.71728 -0.69678 0.4722  0.001 ***
## pho -0.99897  0.04533 0.1757  0.073 .  
## nit -0.94906 -0.31511 0.4510  0.001 ***
## amm -0.97495  0.22241 0.1762  0.076 .  
## oxy  0.93352 -0.35854 0.6263  0.001 ***
## bod -0.94094  0.33857 0.2237  0.040 *  
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## Permutation: free
## Number of permutations: 999</code></pre>
<pre class="r"><code>plot(spe_ca_env, col = &quot;grey40&quot;)
plot(spe_ca_env, p.max = 0.05, col = &quot;red&quot;) # plot significant variables with a different colour</code></pre>
<p><img src="/collection/quantecol/chapters/09-CA_files/figure-html/unnamed-chunk-13-1.png" width="672" /></p>
<div id="questions" class="section level3">
<h3>Questions</h3>
<blockquote>
<p><strong>Question 1.</strong> How would you explain the patterns seen in the four panels of the above figure?</p>
</blockquote>
<blockquote>
<p><strong>Question 2.</strong> Apply approaches taken from the analysis shown immediately above to these datasets: 1. <a href="https://www.davidzeleny.net/anadat-r/doku.php/en:data:ybirds">bird communities along elevation gradient in Yushan Mountain, Taiwan</a>; 2. <a href="https://www.davidzeleny.net/anadat-r/doku.php/en:data:aravo">alpine plant communities in Aravo, France</a>.</p>
</blockquote>
<blockquote>
<p><strong>Question 3.</strong> Discuss the patterns observed, and explain the ordination diagrams with particular reference to how the species are influenced by the major environmental drivers.</p>
</blockquote>
<p>Submit an R script wherein you provide answers to these questions by no later than 17:00 on Friday 16 July 2021.</p>
</div>
</div>

      </section>
      <footer class="post-footer">
        <div class="post-pagination dt w-100 mt4 mb2">
  
  
    <a class="prev dtc pr2 tl v-top fw6"
    href="/collection/quantecol/chapters/08-pca_sdg/">&larr; 8b. PCA of WHO SDGs</a>
  
  
  
    <a class="next dtc pl2 tr v-top fw6"
    href="/collection/quantecol/chapters/10-pcoa/">10. Principal Coordinate Analysis (PCoA) &rarr;</a>
  
</div>

      </footer>
    </article>
    
  </section>
</main>

<aside class="page-sidebar" role="complementary">
                         
 











  <img src="/collection/featured-sidebar.jpg" class="db ma0">

                         
 



<div class="flex items-start sticky ph4 pb4 flex-row">
  <div class="w-two-thirds w-50-l ph0">
    <h2 class="mv3 f5 fw7 ttu tracked">
      <a class="no-underline dim" href="/collection/">Outline</a></h2>
    <nav id="SectionTableOfContents" aria-label="SectionTableOfContents">
        <ul>
        
          
          
          
          <details  class="">
            <summary class="" hugo-nav="/collection/intro_r/"><a href="/collection/intro_r/">BCB744 (Intro R)</a></summary>
            
              
              <li class="" hugo-nav="/collection/intro_r/chapters/02-rstudio/"><a href="/collection/intro_r/chapters/02-rstudio/">1. RStudio and R</a></li>
            
              
              <li class="" hugo-nav="/collection/intro_r/chapters/03-github/"><a href="/collection/intro_r/chapters/03-github/">2. GitHub</a></li>
            
              
              <li class="" hugo-nav="/collection/intro_r/chapters/04-workflow/"><a href="/collection/intro_r/chapters/04-workflow/">3. An R workflow</a></li>
            
              
              <li class="" hugo-nav="/collection/intro_r/chapters/05-graphics/"><a href="/collection/intro_r/chapters/05-graphics/">4. Graphics with ggplot2</a></li>
            
              
              <li class="" hugo-nav="/collection/intro_r/chapters/06-faceting/"><a href="/collection/intro_r/chapters/06-faceting/">5. Faceting figures</a></li>
            
              
              <li class="" hugo-nav="/collection/intro_r/chapters/07-brewing/"><a href="/collection/intro_r/chapters/07-brewing/">6. Brewing colours</a></li>
            
              
              <li class="" hugo-nav="/collection/intro_r/chapters/08-mapping/"><a href="/collection/intro_r/chapters/08-mapping/">7. Mapping with ggplot2</a></li>
            
              
              <li class="" hugo-nav="/collection/intro_r/chapters/09-mapping_style/"><a href="/collection/intro_r/chapters/09-mapping_style/">8. Mapping with style</a></li>
            
              
              <li class="" hugo-nav="/collection/intro_r/chapters/10-mapping_openstreetmap/"><a href="/collection/intro_r/chapters/10-mapping_openstreetmap/">9. Mapping with OpenStreetMap</a></li>
            
              
              <li class="" hugo-nav="/collection/intro_r/chapters/11-tidy/"><a href="/collection/intro_r/chapters/11-tidy/">10. Tidy data</a></li>
            
              
              <li class="" hugo-nav="/collection/intro_r/chapters/12-tidier/"><a href="/collection/intro_r/chapters/12-tidier/">11. Tidier data</a></li>
            
              
              <li class="" hugo-nav="/collection/intro_r/chapters/13-tidiest/"><a href="/collection/intro_r/chapters/13-tidiest/">12. Tidiest data</a></li>
            
              
              <li class="" hugo-nav="/collection/intro_r/chapters/14-recap/"><a href="/collection/intro_r/chapters/14-recap/">13. Recap</a></li>
            
              
              <li class="" hugo-nav="/collection/intro_r/chapters/15-functions/"><a href="/collection/intro_r/chapters/15-functions/">14. Functions by chapter</a></li>
            
              
              <li class="" hugo-nav="/collection/intro_r/chapters/16-base_r/"><a href="/collection/intro_r/chapters/16-base_r/">15. Base R primer</a></li>
            
              
              <li class="" hugo-nav="/collection/intro_r/chapters/17-dates/"><a href="/collection/intro_r/chapters/17-dates/">16. Dates</a></li>
            
          </details>
          
          </li>
        
          
          
          
          <details  class="">
            <summary class="" hugo-nav="/collection/biostats/"><a href="/collection/biostats/">BCB744 (Biostats)</a></summary>
            
              
              <li class="" hugo-nav="/collection/biostats/chapters/02-data/"><a href="/collection/biostats/chapters/02-data/">1. Types of data</a></li>
            
              
              <li class="" hugo-nav="/collection/biostats/chapters/03-descriptive/"><a href="/collection/biostats/chapters/03-descriptive/">2. Central tendency and dispersion</a></li>
            
              
              <li class="" hugo-nav="/collection/biostats/chapters/04-graphics/"><a href="/collection/biostats/chapters/04-graphics/">3. Graphical data displays</a></li>
            
              
              <li class="" hugo-nav="/collection/biostats/chapters/06-t_tests/"><a href="/collection/biostats/chapters/06-t_tests/">5. Inferences about one or two populations</a></li>
            
              
              <li class="" hugo-nav="/collection/biostats/chapters/07-anova/"><a href="/collection/biostats/chapters/07-anova/">6. Analysis of Variance (ANOVA)</a></li>
            
              
              <li class="" hugo-nav="/collection/biostats/chapters/08-regressions/"><a href="/collection/biostats/chapters/08-regressions/">7. Simple linear regressions</a></li>
            
              
              <li class="" hugo-nav="/collection/biostats/chapters/09-correlations/"><a href="/collection/biostats/chapters/09-correlations/">8. Correlation</a></li>
            
              
              <li class="" hugo-nav="/collection/biostats/chapters/10-confidence/"><a href="/collection/biostats/chapters/10-confidence/">9. Confidence intervals</a></li>
            
              
              <li class="" hugo-nav="/collection/biostats/chapters/11-transformations/"><a href="/collection/biostats/chapters/11-transformations/">10. Data transformations</a></li>
            
          </details>
          
          </li>
        
          
          
          
          <details open class="active">
            <summary class="active" hugo-nav="/collection/quantecol/"><a href="/collection/quantecol/">BCB743</a></summary>
            
              
              <li class="" hugo-nav="/collection/quantecol/chapters/01-data/"><a href="/collection/quantecol/chapters/01-data/">1. Multivariate data</a></li>
            
              
              <li class="" hugo-nav="/collection/quantecol/chapters/02-biodiversity/"><a href="/collection/quantecol/chapters/02-biodiversity/">2. Biodiversity</a></li>
            
              
              <li class="" hugo-nav="/collection/quantecol/chapters/03-deep_dive/"><a href="/collection/quantecol/chapters/03-deep_dive/">3. Deep Dive into Gradients</a></li>
            
              
              <li class="" hugo-nav="/collection/quantecol/chapters/04-env_dist/"><a href="/collection/quantecol/chapters/04-env_dist/">4. Environmental Distance</a></li>
            
              
              <li class="" hugo-nav="/collection/quantecol/chapters/05-spp_dissimilarity/"><a href="/collection/quantecol/chapters/05-spp_dissimilarity/">5. Species Dissimilarities</a></li>
            
              
              <li class="" hugo-nav="/collection/quantecol/chapters/06-correlations/"><a href="/collection/quantecol/chapters/06-correlations/">6. Correlations and Associations</a></li>
            
              
              <li class="" hugo-nav="/collection/quantecol/chapters/08_pca/"><a href="/collection/quantecol/chapters/08_pca/">8a. Principal Component Analysis (PCA)</a></li>
            
              
              <li class="" hugo-nav="/collection/quantecol/chapters/08-pca_sdg/"><a href="/collection/quantecol/chapters/08-pca_sdg/">8b. PCA of WHO SDGs</a></li>
            
              
              <li class="active" hugo-nav="/collection/quantecol/chapters/09-ca/"><a href="/collection/quantecol/chapters/09-ca/">9. Correspondence Analysis (CA)</a></li>
            
              
              <li class="" hugo-nav="/collection/quantecol/chapters/10-pcoa/"><a href="/collection/quantecol/chapters/10-pcoa/">10. Principal Coordinate Analysis (PCoA)</a></li>
            
              
              <li class="" hugo-nav="/collection/quantecol/chapters/11-nmds/"><a href="/collection/quantecol/chapters/11-nmds/">11a. non-Metric multidimensional scaling (nMDS)</a></li>
            
              
              <li class="" hugo-nav="/collection/quantecol/chapters/11-nmds_diatoms/"><a href="/collection/quantecol/chapters/11-nmds_diatoms/">11b. nMDS of Mayombo&#39;s diatom data</a></li>
            
              
              <li class="" hugo-nav="/collection/quantecol/chapters/12-constrained_ordination/"><a href="/collection/quantecol/chapters/12-constrained_ordination/">12. Constrained Ordination</a></li>
            
              
              <li class="" hugo-nav="/collection/quantecol/chapters/13-cluster_analysis/"><a href="/collection/quantecol/chapters/13-cluster_analysis/">13. Cluster analysis</a></li>
            
          </details>
          
          </li>
        
        </ul>
    </nav>
  </div>
  <details id="PageTableOfContents">
    <summary><h2 class="mv0 f5 fw7 ttu tracked dib">On this page<h2></summary>
    <div class="pl2 pr0 mh0">
    
    </div>
  </details>
  
</div>

</aside>

<footer class="site-footer pv4 bt b--transparent ph5" role="contentinfo">
  <nav class="db dt-l w-100">
    <p class="site-copyright f7 db dtc-l v-mid w-100 w-33-l tc tl-l pv2 pv0-l mv0 lh-copy">
      &copy; 2022 University of the Western Cape, Cape Town
      <span class="middot-divider"></span>
      Made with <span xmlns:dct="http://purl.org/dc/terms/" property="dct:title"><a xmlns:dct="http://purl.org/dc/terms/" href="https://github.com/hugo-apero/" rel="dct:source">Hugo Apéro</a></span>.
      <br />
      
Based on <span xmlns:dct="http://purl.org/dc/terms/" property="dct:title"><a xmlns:dct="http://purl.org/dc/terms/" href="https://github.com/formspree/blogophonic-hugo" rel="dct:source">Blogophonic</a></span> by <a xmlns:cc="http://creativecommons.org/ns#" href="https://formspree.io" property="cc:attributionName" rel="cc:attributionURL">Formspree</a>.
    </p>
    
    <div class="site-social-links db dtc-l v-mid w-100 w-33-l tc pv2 pv0-l mv0">
      <div class="social-icon-links" aria-hidden="true">
  
  
    
    
    
      
    
    
    
    
    
      
    
    <a class="link dib h1 w1 ml0 mr2 f6 o-90 glow" href="https://github.com/ajsmit/" title="github" target="_blank" rel="noopener">
      <i class="fab fa-github fa-lg fa-fw"></i>
    </a>
  
    
    
    
    
    
    
    
      
    
    <a class="link dib h1 w1 ml0 mr2 f6 o-90 glow" href="http://orcid.org/0000-0002-3799-6126" title="orcid" target="_blank" rel="noopener">
      <i class="ai ai-orcid fa-lg fa-fw"></i>
    </a>
  
    
    
    
    
    
    
    
      
    
    <a class="link dib h1 w1 ml0 mr2 f6 o-90 glow" href="https://www.researchgate.net/profile/Albertus-Smit" title="researchgate" target="_blank" rel="noopener">
      <i class="ai ai-researchgate fa-lg fa-fw"></i>
    </a>
  
    
    
    
    
    
    
    
      
    
    <a class="link dib h1 w1 ml0 mr2 f6 o-90 glow" href="https://uwc.academia.edu/AlbertusSmit" title="academia" target="_blank" rel="noopener">
      <i class="ai ai-academia fa-lg fa-fw"></i>
    </a>
  
    
    
    
    
    
    
    
      
    
    <a class="link dib h1 w1 ml0 mr2 f6 o-90 glow" href="https://scholar.google.co.za/citations?user=ATsBBKoAAAAJ&amp;hl=en" title="google-scholar" target="_blank" rel="noopener">
      <i class="ai ai-google-scholar fa-lg fa-fw"></i>
    </a>
  
    
    
    
      
    
    
    
    
    
      
    
    <a class="link dib h1 w1 ml0 mr2 f6 o-90 glow" href="https://www.instagram.com/ajsmit/" title="instagram" target="_blank" rel="noopener">
      <i class="fab fa-instagram fa-lg fa-fw"></i>
    </a>
  
</div>

    </div>
    
    <div class="site-links f6 db dtc-l v-mid w-100 w-67-l tc tr-l pv2 pv0-l mv0">
      
      <a class="dib pv1 ph2 link" href="/license/" title="License">License</a>
      
      <a class="dib pv1 ph2 link" href="/contact/" title="Contact form">Contact</a>
      
      <a class="dib pv1 ph2 link" href="/contributors/" title="Contributors">Contributors</a>
      
    </div>
  </nav>
  
    <script>

    var i, text, code, codes = document.getElementsByTagName('code');
    for (let i = 0; i < codes.length;) {
      code = codes[i];
      if (code.parentNode.tagName !== 'PRE' && code.childElementCount === 0) {
        text = code.textContent;
        if (/^\$[^$]/.test(text) && /[^$]\$$/.test(text)) {
          text = text.replace(/^\$/, '\\(').replace(/\$$/, '\\)');
          code.textContent = text;
        }
        if (/^\\\((.|\s)+\\\)$/.test(text) ||
            /^\\\[(.|\s)+\\\]$/.test(text) ||
            /^\$(.|\s)+\$$/.test(text) ||
            /^\\begin\{([^}]+)\}(.|\s)+\\end\{[^}]+\}$/.test(text)) {
          code.outerHTML = code.innerHTML;  
          continue;
        }
      }
      i++;
    }
</script>

  
    
    
      <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/katex@0.13.13/dist/katex.min.css" integrity="sha384-RZU/ijkSsFbcmivfdRBQDtwuwVqK7GMOw6IMvKyeWL2K5UAlyp6WonmB8m7Jd0Hn" crossorigin="anonymous">
<script defer src="https://cdn.jsdelivr.net/npm/katex@0.13.13/dist/katex.min.js" integrity="sha384-pK1WpvzWVBQiP0/GjnvRxV4mOb0oxFuyRxJlk6vVw146n3egcN5C925NCP7a7BY8" crossorigin="anonymous"></script>
<script defer src="https://cdn.jsdelivr.net/npm/katex@0.13.13/dist/contrib/auto-render.min.js" integrity="sha384-vZTG03m+2yp6N6BNi5iM4rW4oIwk5DfcNdFfxkk9ZWpDriOkXX8voJBFrAO7MpVl" crossorigin="anonymous" onload="renderMathInElement(document.body);"></script>



    
  
  
</footer>

      </div>
    </body>
</html>
