---
title: "Descriptives Exercises"
subtitle: ""  
author: 
  - "AJ Smit"
date: '`r Sys.Date()`'
output:
  xaringan::moon_reader:
    css:
      - default
      - "default-fonts.css"
      - ki
      - "uwc_logo.css"
    yolo: false
    self_contained: TRUE  
    lib_dir: libs
    nature:
      highlightStyle: idea
      highlightLines: true
      highlightLanguage: r
      countIncrementalSlides: false
      ratio: 16:9
---

```{r setup, include=FALSE, echo=FALSE} 
library(tidyverse)
library(ggpubr)
knitr::opts_chunk$set(echo = TRUE,
                      comment = "R>",
                      message = FALSE,
                      warning = FALSE,
                      include = TRUE,
                      fig.retina = 3,
                      fig.width = 6,
                      fig.height = 3.6,
                      fig.align = "center")
```

.left-column[
# Question 1
]

.right-column[
* Use the 'BeachBirds.csv' dataset. For each bird species and sex (i.e. `Species` x `Sex`), calculate the summary statistics mean, median, standard error, standard deviation, and first and third quartiles for both measured variables (`flush.dist` and `land.dist`).
]

---

.left-column[
# Question 2
]

.right-column[
* Using the 'BeachBirds.csv' data, create a panel of four graphs similar to the ones shown above. I.e. for each bird species A) a scatterplot of 'raw values' and the corresponding means; B) a bar graph with whiskers; C) a box-and-whisker plot; and D) box-and-whisker plots that also take into account the birds' sex. Use only one of the measurement variables.
]

---

.left-column[
# Question 3
]

.right-column[
* Notice how the data summary for chicken weights contained within `wt_summary` is very similar to the summary returned for `weight` when we apply `summary(chicks)`. Please use the `summarise()` approach and construct a data summary with exactly the same summary statistics for `weight` as that which `summary()` returns.
]
