---
title: "*t*-test Exercises"
subtitle: ""  
author: 
  - "AJ Smit"
date: '`r Sys.Date()`'
output:
  xaringan::moon_reader:
    css:
      - default
      - "default-fonts.css"
      - ki
      - "uwc_logo.css"
    yolo: false
    self_contained: TRUE  
    lib_dir: libs
    nature:
      highlightStyle: idea
      highlightLines: true
      highlightLanguage: r
      countIncrementalSlides: false
      ratio: 16:9
---

```{r setup, include=FALSE, echo=FALSE} 
library(tidyverse)
library(ggpubr)
knitr::opts_chunk$set(echo = TRUE,
                      comment = "R>",
                      message = FALSE,
                      warning = FALSE,
                      include = TRUE,
                      fig.retina = 3,
                      fig.width = 6,
                      fig.height = 3.6,
                      fig.align = "center")
```

.left-column[
# Question 1
]

.right-column[
* Use a suitable R function to generate two samples of normal data (use n = 100) to represent a fictituous experiment. Describe this 'experiment' in a paragraph of no longer than 10 lines of text. Write a corresponding hypothesis (H0 and Ha). Display the data for the two samples using histograms and box and whisker plots. Test the hypothesis using an appropriate two-side test, and write a one sentence conclusion for your findings, together with the proper reporting of the results. Provide all of the code used to accomplish this.
]

---

.left-column[
# Question 2
]

.right-column[
* Search for a built-in R dataset suitable for a t-test. Which t-test is appropriate for testing hypotheses about these data? Write down the hypothesis and test it.
]
